### PR TITLE
Clarify what allowusermedia actually does.

### PR DESCRIPTION
**Pull request by clelland**
This updates the html integration section on 'allowusermedia', and
describes more clearly how it affects the generated policy for both
camera and microphone features.

Fixes: #153

### CODE REVIEW

**Comment by annevk** [comment]
These are statements of facts. Where are the corresponding implementation requirements?

**Comment by clelland** [comment]
That's a good point; this text does just describe what happens when the attribute is used. The actual processing requirements for the attribute are in [8.5. Process feature policy attributes](https://wicg.github.io/feature-policy/#process-feature-policy-attributes), but aren't affected by this clarification.

I'm wondering if all of that kind of text (non-normative, since it's just describing the effects of the algorithms that are listed later) should be removed from the spec, or relegated into notes. Would that make the spec more useful from an implementer's perspective, do you think?

**Comment by annevk** [comment]
I think you want to mark it clearly as being non-normative to avoid giving the impression this is what you need to turn into an implementation. I usually start out with just requirements and notes for clarifications. And then maybe at some point an introduction when things have settled down a bit.

**Comment by jan-ivar** [comment]
Does `allowusermedia` add any practical value over `allow="camera"`?

If not, [no browser](https://wpt.fyi/results/html/dom/interfaces.https.html%3Finclude%3DHTML.*?label=stable&aligned=true) implements `allowusermedia` AFAIK, so maybe we can drop it?

**Comment by clelland** [comment]
I think we still need it, at least as long as `allowusermedia` is in HTML.

I've looked for an issue / PR on the WHATWG repo for removing that, if it's really completely unsupported, but haven't found one yet. If there really isn't one already, I'll open it.

**Comment by jan-ivar** [comment]
@clelland I'll open one.

**Comment by clelland** [comment]
And to answer your earlier question, @jan-ivar, no, I don't think that `allowusermedia` adds significant value, other than for being shorthand for `allow="camera *; microphone *"`.

**Comment by clelland** [comment]
Closing, as `allowusermedia` has been removed from HTML in https://github.com/whatwg/html/commit/95e72ce392c8d8afab1b85468766f41751691f64

**Pull request closed without merging**
