### PR TITLE
change status to fpwd

### PR DESCRIPTION
**Pull request by samuelweiler**

### CODE REVIEW

**Comment by clelland** [comment]
Should the 'missing TR entry' error be fixed before merging this, or does that matter at all at this point?

**Comment by samuelweiler** [comment]
Yes, it needs to be fixed.  Do not merge yet.

**Comment by clelland** [comment]
Holding off on the merge until I get the go-ahead from W3C :)

**Comment by clelland** [comment]
Hey @samuelweiler, what's the status on this? Does it need to be merged, or was this just necessary to get the FPWD published?

**Comment by samuelweiler** [comment]
Yes, this should be merged.

**Pull request merged**
